# .pre-commit-config.yaml

repos:
  # Basic hooks from pre-commit-hooks repository (generic file checks)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest stable version
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespaces
      - id: end-of-file-fixer    # Ensures files end with a newline
      - id: check-added-large-files  # Prevents adding files larger than 500KB
      - id: check-merge-conflict  # Checks if there are leftover merge conflict markers

  # Black for code formatting
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use the latest stable version
    hooks:
      - id: black
        args: [--line-length=88]  # Adjust line length according to your project style

  # Flake8 for linting Python code
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0  # Use the latest stable version
    hooks:
      - id: flake8
        args:
          - --max-line-length=88  # Keep line length consistent with Black
          - --ignore=E203,W503  # Optional: Ignore specific PEP8 warnings

  # isort for import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use the latest stable version
    hooks:
      - id: isort
        args: [--profile=black]  # Ensure imports are sorted according to Black's style
