# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace  # Removes trailing whitespaces
      - id: end-of-file-fixer    # Ensures files end with a newline
      - id: check-yaml           # Ensures valid YAML files
      - id: check-added-large-files  # Prevents adding large files accidentally
